version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "package"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "package"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:20"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
